From github.com:baranidlo/bench
 * branch            gh-pages   -> FETCH_HEAD
Already up-to-date.
Moving old 'tournaments' to 'tournaments.old'...
Downloading new 'tournaments' file...
--2019-12-08 07:04:24--  http://lists.starwarsclubhouse.com/api/v1/tournaments
Resolving lists.starwarsclubhouse.com (lists.starwarsclubhouse.com)... 35.173.69.207
Connecting to lists.starwarsclubhouse.com (lists.starwarsclubhouse.com)|35.173.69.207|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-12-08 07:04:24 ERROR 404: Not Found.

Downloading new tournament list data...
Traceback (most recent call last):
  File "./diff_tournaments.py", line 33, in <module>
    diffFiles(sys.argv[1], sys.argv[2])
  File "./diff_tournaments.py", line 14, in diffFiles
    old_tournament_data = json.load(o)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
